cache:
  paths:
  - vendor/

variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Paris"

before_script:
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" 2> /dev/null
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" 2> /dev/null
  - php composer-setup.php 2> /dev/null
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');" 2> /dev/null
  - php composer.phar install 2> /dev/null

test:qualityControl:
  tags:
    - test
  image: php:7.1-cli-alpine3.4
  script:
    #- find . -path ./vendor -prune -o -type f -name '*.php' -print0 | sort | xargs -0 php -l
    - php -f vendor/bin/phpmd ./ text ./phpmd.xml --exclude vendor/
    - php vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml src
    - php vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml specs

test:atoum:
  tags:
    - test
  image: php:7.1-cli-alpine3.4
  script:
    - php -f vendor/bin/atoum
