language: php
php:
  - 7.1
before_script:
  - composer install
script:
  - vendor/bin/phpmd ./ text ./phpmd.xml --exclude vendor/
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml src
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml specs
  - vendor/bin/atoum
